jasypt:
  encryptor:
    bean: jasyptStringEncryptor
aws:
  credentials:
    access-key:
    secret-key:
    region: ap-northeast-2
  s3:
    bucket:
spring:
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
  datasource:
    url: ENC(QjwiP9PmfCOI3a1Qc8ZfzDzT7ZzLrByDZenkCc3W6b7bGn3YjzLGbe+3m6FvAejqejdmTY2KYuwNGL/RkH5ysPIkw5WStvfb)
    username: ENC(L0kzYFpSX3w8Kp4vGkamFw==)
    password: ENC(+l0rNkHYeHjfoTmkxYate/tZxZ+6B/KM)
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
            redirectUri:
    user:
      name:
      password:
