jasypt:
  encryptor:
    bean: jasyptStringEncryptor
aws:
  credentials:
    access-key: ENC(AXGXcyGl8zSV0o1f2tjKJmyaMN75vjtNm+PGZU74exk=)
    secret-key: ENC(D/7U1Y5JXDAYhq1PZfSzDFPooxrVEIfsz6B6HE7g1FNpqubJyKuqUhyEOULGbBNFxNm4NZkd6kk=)
    region: ap-northeast-2
  s3:
    bucket: ENC(DkFZypoaguNPKzi+G7VWxVUZb7uYM/xPo/SBS+h9xL64oEIj/MN7Hw==)
spring:
  logging:
    level:
      root: DEBUG
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
  datasource:
    url: ENC(I9TKx8Daa4fCYGCqGTw4pUUlN4I0QdVTJ221LUufBoCxgv6GTfgQuA==)
    username: ENC(KhRy3S/TJEnxXRHYaWpGVA==)
    password: ENC(LsKxRtS99poEPCyCl7bbUg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    token:
      secret-key: ENC(splgClZ0/GF97Phs3Y+wyoKe0+/02DauHDVHznqHY6L7TGcHylZGXj6ljNvaBJqEMekM68X47uOZeYTZT90tUQ==)
      expire-length: ENC(S3cUIoNjjoBYhjMbWum1oA==)
oauth2:
  user:
    github:
      client-id: bbdc7d55a4bad1b5bae9
      client-secret: ENC(enLB/MEvcV/Iu77ZcKFW1V5TcOWiIZmRX8MEj1y0LnKyMBgfl1Xm80Cr8f7K+XiI6sp49D6mbTk=)
      redirect-uri: http://localhost:8080/redirect/oauth
    github-ios:
      client-id: 3ac935cf627da08c8f03
      client-secret: ENC(kyC9uQKjyK8/mYRKOpBinQqdNqRtF2jW6fZrxPaL+4/TNct7CFQDcA6BL38+Gy94JY64lgkxIJ0=)
      redirect-uri: http://localhost:8080/redirect/oauth
  provider:
    github:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
    github-ios:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
