aws:
  credentials:
    access-key:
    secret-key:
    region: ap-northeast-2
  s3:
    bucket:
spring:
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
#  sql:
#    init:
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#      mode: always
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306
#    username: root
#    password: 1234
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
            redirectUri:
    user:
      name:
      password:
#JWT:
#  SECRET:

#logging:
#  level:
#    com:
#      team6:
#        issue_tracker: debug

# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operation-sorter: alpha # alpha(알파벳 오름차순), method(HTTP 메서드순)
    tag-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html  # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**